package com.companyname.earl.photozclone.service;


import com.companyname.earl.photozclone.model.Photo;
import com.companyname.earl.photozclone.repository.PhotozRepository;
import org.springframework.stereotype.Service;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

//@Component
@Service
public class PhotozService {

//    private Map<String, Photo> db = new HashMap<>() {{
//        put("1", new Photo("1", "hello.jpg"));
//    }};

    private final PhotozRepository photozRepository;

    public PhotozService(PhotozRepository photozRepository){
        this.photozRepository = photozRepository;
    }
    public Iterable<Photo> get() {
        return photozRepository.findAll();
    }

    public Photo get(Integer id){
        return photozRepository.findById(id).orElse(null);
    }

    public void remove(Integer id){
        photozRepository.deleteById(id);
    }

    public Photo save(String fileName, String contentType, byte[] data) {
        Photo photo = new Photo();
        photo.setContentType(contentType);
        //photo.setId(UUID.randomUUID().toString()); Not setting id, that will be autogenerated by database
        photo.setFileName(fileName);
        photo.setData(data);
        photozRepository.save(photo);
        return photo;
    }
}
